#include "stdinc.h"
#include "../../client/DCPlusPlus.h"
#include "Fire-ResourceManager.h"
string FireResourceManager::strings[] = {
"Auto-away on minimize (and back on restore)", 
"Fire Settings", 
"Fire Settings", 
"Fire Language file", 
"&Fire", 
"About Fire", 
"Download begins", 
"Download finished", 
"Alternate source added", 
"Upload finished", 
"My nick in mainchat", 
"File is corrupted", 
"Unhandled Exception", 
"Hub connected", 
"Hub disconnected", 
"Favorite user online", 
"Faker found", 
"Typing notification", 
"Sounds Page", 
"Browse...", 
"File", 
"Make an annoying sound every time a private message is received", 
"Make an annoying sound when a private message window is opened", 
};
string FireResourceManager::names[] = {
"FireSettingsAutoAway", 
"FireSettings", 
"MenuFireSettings", 
"SettingsFireLanguageFile", 
"MenuFire", 
"MenuFireAbout", 
"SoundDownloadBegins", 
"SoundDownloadFinished", 
"SoundSourceAdded", 
"SoundUploadFinished", 
"MynickInChat", 
"SoundTthInvalid", 
"SoundException", 
"HubConnected", 
"HubDisconnected", 
"FavuserOnline", 
"SoundFakerFound", 
"SoundTypingNotify", 
"SettingsSounds", 
"Browse", 
"File", 
"SettingsPmBeep", 
"SettingsPmBeepOpen", 
};
string FireResourceManager::stringsTwo[] = {
"Clear chat", 
"Private message sound", 
"None", 
"Fire++", 
"Upload begins", 
"URL Clicked", 
"Test", 
};
string FireResourceManager::namesTwo[] = {
"Clear", 
"SetfiredcPrivateSound", 
"None", 
"SettingsFiredc", 
"SoundStartUpload", 
"SoundUrlClick", 
"Test", 
};
